name: 'Check for monorepo changes'
description: 'See which workspaces in a monorepo have changed'
author: 'Lyra Naeseth'
branding:
  icon: edit
  color: yellow
runs:
  using: 'node16'
  main: 'dist/index.js'
